[pytest]
addopts = 
    --tb=short
    --strict-markers
    --alluredir=allure-results
    --clean-alluredir
    
markers =
    smoke: Smoke tests
    regression: Regression tests
    slow: Slow tests