[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    ui: UI тесты
    api: API тесты
    smoke: Smoke тесты
    search: Тесты поиска
    cart: Тесты корзины
    auth: Тесты авторизации